### ISSUE TITLE
Create a CI/CD tool for automation on deployment

### ISSUE THREAD

**Issue by samxu01** [MubaiHua/CS130-Group-Project#16]
## User Story
As a **user-end developer**, I want to deploy this application outside of my localhost.

## Detailed Description
Enable user-end developer tester to auto-deploy this application in an outside server.

## Tasks
- [x] #17
- [x] #18
- [x] #21
- [x] #26
- [x] #45

**Comment by melodycai1105** [comment]
Task completed
